---
title: "Classification"
author: "Duong Trinh"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
    code_folding: hide
  pdf_document: 
    number_sections: true
    extra_dependencies: ["mathtools","bbm"]
fontsize: 10pt
---


```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format = function() {
  if (knitr::is_latex_output()) 'latex' else 'pandoc'
})
```

<!--- For HTML Only --->
`r if (knitr:::is_html_output()) '
$\\newcommand{\\mathbbm}[1]{\\mathbb{#1}}$
'`

# Performance Metric
For a fixed cutoff $c$, the True Positive Rate is:
$$
TPR(c) = P\{M>c \mid D = 1\}
$$

and the False Positive Rate is:
$$
FPR(c) = P\{M>c \mid D = 0\}
$$

Since the cutoff $c$ is not usually fixed in advance, we can plot the TPR against the FPR for all possible values of $c$. This is exactly what the ROC curve is, $FPR(c)$ on the $x$ axis and $TPR(c)$ along the $y$ axis.


# Illustration
```{r}
# library(pracma) # for a (non-symmetric) Toeplitz matrix
GenRegr <- function(n,p,options) {
  # Generate predictors x
  if (options.corr == 0) {# Uncorrelated predictors
    x = matrix(rnorm(n*p),n,p)
  }
  else if (options.corr == 1) {# Spatially ncorrelated predictors
    C = toeplitz(options.rho^(0:(p-1)))
    x = matrix(rnorm(n*p),n,p)%*%chol(C)
  }
  else {
    print('Wrong choice of options.corr')
  }
  
  x <- data.matrix(sapply(data.frame(x), function(x) {(x-mean(x))/sd(x)})) # Standardize x
  
  # Generate coefficients
  beta <- rep(0,p)
  # beta[1:6] <- c(1.5,-1.5,2,-2,2.5,-2.5)
  beta[1:6] <- rep(2,6)

  
  if (options.corr == 0) {
    signal_y <- sum(beta^2)
  } 
  else if (options.corr == 1) {
    signal_y <- sum((chol(C)%*%beta)^2)
  }
  
  c <- signal_y*((1-options.R2)/options.R2) # mean(sigmasq) is c to obtain desirable options.R2 (or SNR)
  
  # Generate epsilon
  if (options.epsilon == 0) { # iid error
    sigmasq <- c
  } 
  else if (options.epsilon == 1) {
    temp = (x%*%beta)
    sigmasq = c*temp/mean(temp)
  }
  
  epsilon = sqrt(sigmasq) * rnorm(n)
  
  # Generate y
  y = x%*%beta + epsilon
  
  return(list(y = y, x = x, beta = beta, sigmasq = sigmasq))
}
```


```{r}
# Data Generating Process ====
## DGP 2
set.seed(2907)
n = 100
p = 50
options.corr = 0
options.R2 = 0.4
options.epsilon = 0
options.rho = NA

df <- GenRegr(n, p, options)

y <- df$y
X <- df$x
beta_true <-  df$beta
sigmasq_true <- df$sigmasq
```


```{r}
library(Rcpp)
library(RcppArmadillo)
sourceCpp("/Users/duongtrinh/Dropbox/FIELDS/Data Science/R_Data Science/R Practice/CPPDuong/BayesRegrSP.cpp")

sourceCpp("/Users/duongtrinh/Dropbox/FIELDS/Data Science/R_Data Science/R Practice/CPPDuong/BayesRegr.cpp")

resRcpp_st <- BayesRegrSP(y,X,nsave=10000,nburn =5000,prior="student-t")
resRcpp_nosp <- BayesRegr(y,X,nsave=10000,nburn =5000)


```

```{r, message=FALSE}
library(tidyverse)
library(purrr)
library(ggplot2)
library(gridExtra)

resRcpp <- resRcpp_st
# resRcpp <- resRcpp_nosp


names_beta <- map_chr(1:nrow(resRcpp$betadraws),~paste0("b",.x))

df_beta <- data.frame(t(resRcpp$betadraws)) %>%
  `names<-`(.,names_beta) %>% 
  mutate(nsave = 1:ncol(resRcpp$betadraws)) %>% 
  gather(., beta, value, -c("nsave")) %>% 
  mutate(beta = factor(beta, level = names_beta))

df_para <- data.frame(t(resRcpp$betadraws)) %>%
  `names<-`(.,names_beta) %>% 
  mutate(sigsq = t(resRcpp$sigmasqdraws), nsave = 1:ncol(resRcpp$betadraws))

para_true_mat <- data.frame(t(beta_true),sigmasq_true) %>% `names<-`(.,c(names_beta,"sigsq"))

```


```{r}
df_beta2 <- df_beta %>% group_by(beta) %>% 
  summarise(ub = quantile(value,0.995),
            lb = quantile(value,0.005),
            UB = quantile(value,0.95),
            LB = quantile(value,0.05),
            m = median(value)) %>% 
  mutate(true = beta_true)

ggplot(df_beta2, aes(x = beta, y = m)) +
  geom_point(size = 1, col = "blue") +
  geom_point(aes(x = beta, y = true), size = 1, col = "red", shape = 2) +
  geom_linerange(aes(ymin = LB, ymax = UB), size=1, alpha = 0.5) +
  geom_linerange(aes(ymin = lb, ymax = ub), size=0.3, alpha = 0.5) +
  xlab("beta") +
  ylab("value") +
  ggtitle("Caterpillar plot") +
  # coord_flip() +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
PRpair <- function(th) {
  
  m <- df_beta %>% group_by(beta) %>% 
    summarise(ub = quantile(value, 0.5 + th/2),
            lb = quantile(value, 0.5 - th/2)) %>% 
    transmute(m = as.numeric(lb > 0 | ub < 0))
  
  d <- as.numeric(beta_true != 0)
  
  recall <- sum(m == 1 & d == 1)/sum(d == 1)
  precision <- sum(m == 1 & d == 1)/sum(m == 1)
  
  return(c(recall,precision))
}


grid.th <- seq(0.99,0.70,-0.01)
PRdf <- sapply(grid.th, PRpair)
PRdf <- data.frame(t(PRdf)) %>% 
  mutate(HPD = grid.th) %>% 
  `names<-`(., c("recall", "precision", "HPD"))

plotPR <- ggplot(PRdf, aes(x = recall, y = precision, label = HPD)) +
  geom_point() +
  geom_line() +
  coord_cartesian(xlim = c(0,1), ylim = c(0,1)) +
  geom_text(aes(label = HPD), vjust = 1)

plotPR

PRdf <- na.omit(PRdf)

auprc <- sum(diff(PRdf$recall)*PRdf$precision[-1])
auprc
```


```{r}
PRpair <- function(th) {
  
  names_beta <- map_chr(1:nrow(resRcpp$betadraws),~paste0("b",.x))

  df_beta <- data.frame(t(resRcpp$betadraws)) %>%
    `names<-`(.,names_beta) %>% 
    mutate(nsave = 1:ncol(resRcpp$betadraws)) %>% 
    gather(., beta, value, -c("nsave")) %>% 
    mutate(beta = factor(beta, level = names_beta))
  
  m <- df_beta %>% group_by(beta) %>% 
    summarise(ub = quantile(value, 0.5 + th/2),
            lb = quantile(value, 0.5 - th/2)) %>% 
    transmute(m = as.numeric(lb > 0 | ub < 0))
  
  d <- as.numeric(beta_true != 0)
  
  TP <- sum(m == 1 & d == 1)
  FP <- sum(m == 1 & d == 0)
  FN <- sum(m == 0 & d == 1)
  
  return(c(TP,FP,FN))
}


library(parallel)
detectCores()
mclapply(1:Nsim, )


grid.th <- seq(0.99,0.70,-0.01)
PRdf <- sapply(grid.th, PRpair)
PRdf <- data.frame(t(PRdf)) %>% 
  mutate(HPD = grid.th) %>% 
  `names<-`(., c("recall", "precision", "HPD"))

plotPR <- ggplot(PRdf, aes(x = recall, y = precision, label = HPD)) +
  geom_point() +
  geom_line() +
  coord_cartesian(xlim = c(0,1), ylim = c(0,1)) +
  geom_text(aes(label = HPD), vjust = 1)

plotPR

PRdf <- na.omit(PRdf)

auprc <- sum(diff(PRdf$recall)*PRdf$precision[-1])
auprc
```



